#ENUNCIADO
# HALLAR EL AREA DE UN CUADRADO LEYENDO POR TECLADO EL VALOR DE SU LADO
#DESARROLLADO POR JUAN ALEJANDRO OSORIO OSPINA
#FECHA 08.03.2023
# VERSION 1


#ENTRADA
print ("")
v_lado = input("POR FAVOR DIGITE EL VALOR DEL LADO: ") #LECTURA
v_lado = int (v_lado) #CONVERSION DE TEXTO A ENTERO

print ("")
#PROCESOS
v_area = v_lado * v_lado #CALCULAR EL AREA DEL CUADRADO

#SALIDAS
print ("EL AREA DEL TRIANGULO ES: ", v_area)
