#ENUNCIADO
# HALLAR EL AREA Y EL PERIMETRO DE UN RECTANGULO LEYENDO POR TECLADO EL VALOR DE SUS DOS LADOS
#DESARROLLADO POR JUAN ALEJANDRO OSORIO OSPINA
#FECHA 08.03.2023
# VERSION 1


#ENTRADA
print ("")
v_lado1 = input("POR FAVOR DIGITE EL VALOR DEL PRIMER LADO: ") #LECTURA
v_lado1 = int (v_lado1) #CONVERSION DE TEXTO A ENTERO

print ("")
v_lado2 = input("POR FAVOR DIGITE EL VALOR DEL SEGUNDO LADO: ") #LECTURA
v_lado2 = int (v_lado2) #CONVERSION DE TEXTO A ENTERO

print ("")
#PROCESOS
v_area = v_lado1 * v_lado2 #CALCULAR EL AREA DEL RECTANGULO
v_perimetro = (v_lado1*2) + (v_lado2*2) #CALCULAR EL PERIMETRO DEL RECTANGULO

#SALIDAS
print ("EL AREA DEL RECTANGULO ES: ", v_area)
print ("")
print ("EL PERIMETRO DEL RECTANGULO ES: ", v_perimetro)
print ("")
